numero1, numero2, numero3 = map(int,input().split())
numeros = [numero1, numero2, numero3]
numeros.sort()
print(numeros[0])
print(numeros[1])
print(numeros[2])
print("")
print(numero1)
print(numero2)
print(numero3)